"""Entry point: build and send each recipient's scheduled report.

Recipients, their delivery frequency, and their themes are configured in
config.ini. Run this on a schedule (cron, launchd, Task Scheduler) once a day.
"""

import configparser
import datetime
import sys

import email_formatting
import email_sending
import news
import solar
from generate_response import generate_response_news, generate_response_solar
from settings import load_config

DAILY = 1
IMAGE_CID = "solar_image"
IMAGE_INTRO = "Live image of the Sun from the Solar Dynamics Observatory (SDO):"
DISCLAIMER = (
    "The summaries below were generated by GPT-4 from NOAA space weather data and "
    "recent news articles."
)


def get_date_range(frequency):
    """Return (start, end) as YYYY-MM-DD strings for a daily or weekly report."""
    today = datetime.date.today()

    if frequency == DAILY:
        start = today - datetime.timedelta(days=1)
    elif frequency in (0, 2, 3, 4, 5, 6):
        start = today - datetime.timedelta(days=7)
    else:
        raise ValueError(
            f"Unsupported frequency {frequency!r}. Use 1 for daily, or 0 and 2-6 "
            "for a weekly report on that day of the week."
        )

    return start.strftime("%Y-%m-%d"), today.strftime("%Y-%m-%d")


def is_due_today(frequency, day_of_week):
    """Daily reports are always due; weekly ones only on their configured day."""
    return frequency == DAILY or frequency == day_of_week


def read_recipient(config, recipient):
    """Return (frequency, themes) for a recipient, or None if unconfigured."""
    try:
        frequency = config.getint(recipient, "frequency")
        themes = config.get(recipient, "themes")
    except configparser.NoSectionError:
        print(f"No configuration section found for {recipient}. Skipping.")
        return None
    except ValueError:
        print(f"Frequency for {recipient} is not a number. Skipping.")
        return None

    theme_list = [theme.strip() for theme in themes.split(",") if theme.strip()]
    if not theme_list:
        print(f"No themes configured for {recipient}. Skipping.")
        return None

    return frequency, theme_list


def build_and_send(recipient, frequency, themes):
    """Build this recipient's report and send it. Returns True if sent."""
    start_date, end_date = get_date_range(frequency)

    solar_summary = ""
    news_summary = ""
    attachments = []
    inline_image = None

    if "solar" in themes:
        print(f"Building solar report for {recipient}")
        report = solar.build_report(start_date, end_date)
        solar_summary = generate_response_solar(report.prompt)
        attachments = report.attachments
        inline_image = report.inline_image_path

    if "news" in themes:
        print(f"Building news report for {recipient}")
        prompt = news.build_prompt()
        if prompt:
            news_summary = generate_response_news(prompt)

    if not solar_summary and not news_summary:
        print(f"Nothing to report for {recipient}. Skipping.")
        return False

    html_body = email_formatting.get_html_email_body(
        DISCLAIMER,
        IMAGE_INTRO,
        IMAGE_CID if inline_image else None,
        solar_summary,
        news_summary,
    )

    return email_sending.send_email(
        f"Daily Report for {end_date}",
        html_body,
        recipient,
        attachments,
        inline_image,
        IMAGE_CID if inline_image else None,
    )


def main():
    day_of_week = datetime.date.today().weekday()
    config = load_config()

    recipients = [
        address.strip()
        for address in config.get("Email", "recipients").split(",")
        if address.strip()
    ]

    if not recipients:
        print("No recipients configured in config.ini.")
        return 1

    for recipient in dict.fromkeys(recipients):
        print(f"\nLooking up configuration for {recipient}")

        settings = read_recipient(config, recipient)
        if settings is None:
            continue

        frequency, themes = settings
        if not is_due_today(frequency, day_of_week):
            print(f"{recipient} is not scheduled for today. Skipping.")
            continue

        try:
            build_and_send(recipient, frequency, themes)
        except Exception as err:
            # One recipient failing should not stop the rest of the run.
            print(f"Failed to build the report for {recipient}: {err}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
