"""Entry point: build and send each recipient's scheduled report.

Recipients, their delivery frequency, and their themes are configured in
config.ini. Run this on a schedule (cron, launchd, Task Scheduler) once a day.
"""

import configparser
import datetime
import functools
import sys

import email_formatting
import email_sending
import news
import solar
from generate_response import generate_response_news, generate_response_solar
from settings import load_config

DAILY = 1
IMAGE_CID = "solar_image"
IMAGE_INTRO = "Live image of the Sun from the Solar Dynamics Observatory (SDO):"
DISCLAIMER = (
    "The summaries below were generated by GPT-4 from NOAA space weather data and "
    "recent news articles."
)


def get_date_range(frequency):
    """Return (start, end) as YYYY-MM-DD strings for a daily or weekly report."""
    today = datetime.date.today()

    if frequency == DAILY:
        start = today - datetime.timedelta(days=1)
    elif frequency in (0, 2, 3, 4, 5, 6):
        start = today - datetime.timedelta(days=7)
    else:
        raise ValueError(
            f"Unsupported frequency {frequency!r}. Use 1 for daily, or 0 and 2-6 "
            "for a weekly report on that day of the week."
        )

    return start.strftime("%Y-%m-%d"), today.strftime("%Y-%m-%d")


def is_due_today(frequency, day_of_week):
    """Daily reports are always due; weekly ones only on their configured day."""
    return frequency == DAILY or frequency == day_of_week


def read_recipient(config, recipient):
    """Return (frequency, themes) for a recipient, or None if unconfigured."""
    try:
        frequency = config.getint(recipient, "frequency")
        themes = config.get(recipient, "themes")
    except (configparser.NoSectionError, configparser.NoOptionError) as err:
        print(f"Incomplete configuration for {recipient} ({err}). Skipping.")
        return None
    except ValueError:
        print(f"Frequency for {recipient} is not a number. Skipping.")
        return None

    theme_list = [theme.strip() for theme in themes.split(",") if theme.strip()]
    if not theme_list:
        print(f"No themes configured for {recipient}. Skipping.")
        return None

    return frequency, theme_list


# Several recipients are often due on the same day. Caching lets them share one
# set of downloads and one GPT-4 call per date range instead of paying per head.
@functools.lru_cache(maxsize=None)
def _solar_section(start_date, end_date):
    """Return (summary, attachments, inline_image_path) for a date range."""
    report = solar.build_report(start_date, end_date)
    summary = generate_response_solar(report.prompt)
    return summary, report.attachments, report.inline_image_path


@functools.lru_cache(maxsize=None)
def _news_summary():
    """Return the news summary, or '' if no articles were found."""
    prompt = news.build_prompt()
    return generate_response_news(prompt) if prompt else ""


def build_and_send(recipient, frequency, themes):
    """Build this recipient's report and send it.

    Returns True if sent, False if sending failed, and None if there was
    nothing to report.
    """
    start_date, end_date = get_date_range(frequency)

    solar_summary = ""
    news_summary = ""
    attachments = []
    inline_image = None

    if "solar" in themes:
        print(f"Building solar report for {recipient}")
        solar_summary, attachments, inline_image = _solar_section(
            start_date, end_date
        )

    if "news" in themes:
        print(f"Building news report for {recipient}")
        news_summary = _news_summary()

    if not solar_summary and not news_summary:
        print(f"Nothing to report for {recipient}. Skipping.")
        return None

    html_body = email_formatting.get_html_email_body(
        DISCLAIMER,
        IMAGE_INTRO,
        IMAGE_CID if inline_image else None,
        solar_summary,
        news_summary,
    )

    cadence = "Daily" if frequency == DAILY else "Weekly"
    return email_sending.send_email(
        f"{cadence} Report for {end_date}",
        html_body,
        recipient,
        attachments,
        inline_image,
        IMAGE_CID if inline_image else None,
    )


def main():
    day_of_week = datetime.date.today().weekday()
    config = load_config()

    try:
        configured = config.get("Email", "recipients")
    except (configparser.NoSectionError, configparser.NoOptionError):
        print("config.ini has no [Email] section with a recipients option.")
        return 1

    recipients = [
        address.strip() for address in configured.split(",") if address.strip()
    ]

    if not recipients:
        print("No recipients configured in config.ini.")
        return 1

    failures = 0
    for recipient in dict.fromkeys(recipients):
        print(f"\nLooking up configuration for {recipient}")

        settings = read_recipient(config, recipient)
        if settings is None:
            continue

        frequency, themes = settings
        if not is_due_today(frequency, day_of_week):
            print(f"{recipient} is not scheduled for today. Skipping.")
            continue

        try:
            sent = build_and_send(recipient, frequency, themes)
        except Exception as err:
            # One recipient failing should not stop the rest of the run.
            print(f"Failed to build the report for {recipient}: {err}")
            failures += 1
        else:
            if sent is False:
                failures += 1

    # A non-zero exit code lets cron/systemd surface delivery problems.
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
